trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          anupriya/test:$(tag)  # Use a specific tag for better tracking

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: 'push'
        containerRegistry: 'docker'  # Ensure this matches your registry service connection name
        repository: 'anupriya/test'
        tags: |
          $(tag)